const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: "Fluffy buttermilk pancakes served with maple syrup and a side of fresh berries.",
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: "A classic double cheeseburger with all the fixings, served with a side of fries.",
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: "A monstrous milkshake topped with whipped cream, chocolate sauce, and a cherry on top.",
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: "A delightful combination of crispy bacon, scrambled eggs, toast, and fresh avocado slices.",
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: "An egg-cellent sandwich featuring a fried egg, bacon, lettuce, tomato, and mayo on toasted bread.",
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: "Indulge in a dreamy milkshake made with crushed Oreo cookies, vanilla ice cream, and chocolate drizzle.",
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: "A bacon lover's paradise! Enjoy a hearty serving of crispy bacon strips served with eggs and toast.",
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: "Experience the taste of America with this classic burger featuring a juicy beef patty, cheese, lettuce, tomato, and onion.",
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: "A delightful shake to keep you company during quarantine, made with a blend of your favorite fruits and a touch of sweetness.",
  },
  {
    id: 10,
    title: "momos",
    category: "appetizer",
    price: 10.99,
    img: "./images/item-10.jpeg",
    desc: "Authentic Nepali dumplings filled with a choice of vegetables or meat, served with a spicy dipping sauce.",
  },
  {
    id: 11,
    title: "butter chicken",
    category: "dinner",
    price: 17.99,
    img: "./images/item-11.jpeg",
    desc: "A popular Indian dish made with tender chicken cooked in a creamy tomato-based sauce, served with basmati rice.",
  },
  {
    id: 12,
    title: "dal bhat",
    category: "dinner",
    price: 12.99,
    img: "./images/item-12.jpeg",
    desc: "A traditional Nepali meal consisting of lentil soup (dal), steamed rice (bhat), and a variety of accompanying side dishes.",
  },
];

export default menu;
